### ISSUE TITLE
Improve product scope, purpose, and vision

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#1080]
Over the years marked has expanded in its scope related to features, capabilities, and so on. In preparation for the 1.0 release of Marked, we would like to make it more clear what marked is, is not, and where it is going.

## Features to add??

- [ ] Have lexer generate objects for parsing by extenders
- [ ] Add an option to not escape quotes
- [ ] Add direction property to syntax tree and generated HTML #694 
- [ ] Improve support for scroll syncing by editor vendors #691 
- [ ] Override the way that plain text is rendered #581 
- [ ] Consider the support of macros #445 #466 
- [ ] Allow json output instead of a string #588 
- [ ] Render only parts of the Markdown syntax #571
- [ ] Better support for UTF-8 and international characters #561 #1133 

## Features to deprecate??

- [ ] Header IDs
- [ ] Drop support for the Daring Fireball Perl specification

## See also:

- #963 
- #964 
- #965

**Comment by UziTech** [comment]
This has become out of date
