### ISSUE TITLE
[Tables]: Consolidating issues

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#980]
This issue only exists as a consolidation mechanism for table issues, which are now marked as closed.

See #956

**Comment by Feder1co5oave** [comment]
To do list:

- [ ] missing last empty cell: duplicates #914 #693 #188 
    PR to review: #697 #357 #797 
- [x] #889 #881 need an empty line between paragraph and table: no issue
- [ ] important: escaping `|` inside table cells: #831 #595 #285?
   PR: #639 ?
- [ ] don't generate tbody when no cells are present: #637 
- [ ] hard breaks in table cells (compliant?) #933. PR #519?
- [ ] unclear, to-be-considered PR: #464 
- [ ] feature request: tables inside list items: #811 (supported by gfm)
- [ ] feature request: heading-less tables #349 #484 (not supported by gfm)
    PR: #177 
- [ ] feature request: table captions #674
- [ ] (noncompliant) table extension proposal to set relative width among columns: #816

**Comment by jarrodek** [comment]
About issues #889 #881, how the are resolved? Do I need to put the paragraph or not? Is it closed or not? Is it merged or not? This bundle issue thing creates a lot of confusion here.

**Comment by UziTech** [comment]
@jarrodek We are trying to copy github with `gfm` so tables need to have a blank line or nothing above them.
