### ISSUE TITLE
[Headings]: Consolidate issues

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#981]
This issue reference other issues related to the processing of headings. See #956

**Comment by Feder1co5oave** [comment]
Recap of all still relevant issues concerning headings:

- [x] Headings require a space between the hash `#` and the text, per spec. Duplicates: #909 #729 #692 #687 #670 
- [ ] #526 this is ambiguous, I'd like to comply with [commonmark](http://spec.commonmark.org/0.28/#example-42) here
- [ ] complains about duplicate auto-generated ids (see https://github.com/chjj/marked/issues/919#issuecomment-355462033): #919 #879 
- [x] generic complains about auto-generated ids (see https://github.com/chjj/marked/issues/432#issuecomment-49196231): #316 #432 #604 #806 #685 #857 
- [ ] #456 is still relevant IMO, I need to produce some test cases. Fixes #450 #510 
- [x] #971 solved

**Comment by GenaBitu** [comment]
About the requirement of a space after # for headings: I know the space is required by the spec, but why not add an option allowing the space to be omitted (defaulting to false, i. e. requiring the space). I am using this in an editor for relative noobs and would prefer to have the option, while others might stick to the spec.

Will try to post a PR for this.

**Comment by Feder1co5oave** [comment]
@GenaBitu you can parse with `gfm: false`

**Comment by GenaBitu** [comment]
@Feder1co5oave Yes, but then you don't get the rest of GFM, right?

**Comment by Feder1co5oave** [comment]
_Exactly_

**Comment by UziTech** [comment]
You could create an extension as an npm package that could be shared

```js
const marked = require('marked-no-header-space')(require('marked'));
```

`require('marked-no-header-space')` could return a function that extends marked then returns the extended marked.

Problem solved for anyone who wants it and we don't have to work around another option that is not in the spec.
