### ISSUE TITLE
[Code blocks]: Consolidate issues

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#983]
This issue consolidates reference to issues and PRs related to code blocks. Issues will be closed, PRs will be left open, if no merge conflicts exist. See #956

**Comment by mercmobily** [comment]
Josh, this means that all of these issues are _still_ valid and unresolved, even though they are marked as "closed". Right?

**Comment by joshbruce** [comment]
Pretty much. Given the issues span 5+ years I figured this was a good way to put them in one place to maybe put a checklist together to say, "We have tests in the current codebase that demonstrate this is no longer a problem." (I think the community was getting overwhelmed by the sheer number of open issues and maybe not knowing where to begin to contribute back.)

So, if you're looking to contribute, it might be pretty simple. If there's no test to measure the validity - then, it's not resolved - so, it may be as simple as writing a test, verifying it passes, then submitting the PR. If there's a test already - then we can remove it from the reference list.

Hope that makes sense.

**Comment by joshbruce** [comment]
@mercmobily: Shorter version. I don't know if they're resolved or not. Kinda hoping the community will help out on that score. One or two people can't do all the heavy lifting...as has been evidenced. So, I'm taking a somewhat different tack with things. :)

**Comment by jmduke** [comment]
I'm not sure if this is helpful (and I'd be happy to delete the comment if not), but here's a base case of how marked differs from most implementations:

https://johnmacfarlane.net/babelmark2/?text=%3Ch1%3ETest%3C%2Fh1%3E%0A++++++++++++%3Cp%3EShould+this+code+be+in+a+pre+block%3F%3C%2Fp%3E

This has bit me a couple times and I couldn't find specific settings that would resolve it (and though babelmark is testing against 0.2.6 I'm seeing the same behavior on 0.3.9.)

**Comment by Feder1co5oave** [comment]
- [ ] issues demanding a working/better default behavior when highlighting code: #393 #350 #810 #803 
    Possible solution: #418 ?
- [ ] #645 to be fixed to comply with CM. Duplicate #931 
- [ ] #644 not easily fixable
- [ ] #501 codespan not rendering
- [ ] #503 is still a bug, I need to rebase, resolve conflicts and add tests
